AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sendMessage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.sendMessage
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::559308092655:role/lambda-cognito-ses-access'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /sendMessage
            Method: POST
      Environment:
        Variables:
          USER_POOL: us-west-2_s022EVDC7
