AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchPosts:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.searchPosts
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::559308092655:role/lambda_dynamodb_role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /posts/search
            Method: GET
      Environment:
        Variables:
          INDEX_NAME: group-updatedDateTime-index
          TABLE_NAME: forsale-posts
