AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getPost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.getPost
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::559308092655:role/lambda-dynamodb-cognito-access'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/posts/{postid}'
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: forsale-posts
          USER_POOL: us-west-2_s022EVDC7
