AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  updatePost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.updatePost
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::559308092655:role/lambda_dynamodb_role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/posts/{postid}'
            Method: PATCH
        Api2:
          Type: Api
          Properties:
            Path: '/posts/{postid}'
            Method: PUT
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Environment:
        Variables:
          TABLE_NAME: forsale-posts
